import {useState} from 'react'
import { nanoid } from 'nanoid'
import {Form, Button, Container, Card} from 'react-bootstrap'
import { useNavigate } from 'react-router-dom' 


function AddProduct({onAdd}) {
    const [title, setTitle] = useState('')
    const navigate = useNavigate()

    const handleSubmit = (e) => {
        e.preventDefault()

        const newProduct = {
            id: nanoid(),
            title: title,
            price: 0.00,
            description: "New product description", 
            image: 'https://placehold.co/400',
            category: "None"
        }
        onAdd(newProduct)
        navigate('/products')
    }

    return (
        <Container className='mt-5' style={{maxWidth: '500px'}}>
            <Card className='shadow'>
                <Card.Body>
                    <Card.Title className='mb-4'>Add New Product</Card.Title>
                    <Form onSubmit={handleSubmit}>
                        <Form.Group className='mb-3'>
                            <Form.Label>Product Title</Form.Label>
                                <Form.Control
                                type='text'
                                placeholder='Enter title'
                                required
                                value={title}
                                onChange={(e) => setTitle(e.target.value)} />
                                <Form.Text className='text-muted'>
                                    Will be generated by NanoID.
                                </Form.Text>
                        </Form.Group>
                    
                        <div className="d-flex gap-2">
                            <Button variant='primary' type="submit">Create Product</Button>
                            <Button variant='secondary' onClick={() => navigate('/products')}>Cancel</Button>
                        </div>
                    </Form>
                </Card.Body>
            </Card>
        </Container>
    )
}

export default AddProduct